{% set version = '1.0.10' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-iterators
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/iterators_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/iterators/iterators_{{ version }}.tar.gz
  sha256: a9e1b2302828d4527766ce12fa9ae06faf8d51e819a43f8efef632b6ddf471e8

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  noarch: generic

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: RUnit, foreach
requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base

  run:
    - r-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('iterators')"           # [not win]
    - "\"%R%\" -e \"library('iterators')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=iterators
  license: Apache License (== 2.0)
  summary: Support for iterators, which allow a programmer to traverse through all the elements
    of a vector, list, or other collection of data.
  license_family: APACHE

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: iterators
# Type: Package
# Title: Provides Iterator Construct for R
# Version: 1.0.10
# Authors@R: c(person("Rich", "Calaway", role="cre", email="richcala@microsoft.com"), person("Revolution", "Analytics", role=c("aut", "cph")), person("Steve", "Weston", role="aut"))
# Description: Support for iterators, which allow a programmer to traverse through all the elements of a vector, list, or other collection of data.
# Depends: R (>= 2.5.0), utils
# Suggests: RUnit, foreach
# License: Apache License (== 2.0)
# Author: Rich Calaway [cre], Revolution Analytics [aut, cph], Steve Weston [aut]
# Maintainer: Rich Calaway <richcala@microsoft.com>
# Repository: CRAN
# Repository/R-Forge/Project: foreach
# Repository/R-Forge/Revision: 34
# Repository/R-Forge/DateTimeStamp: 2018-05-24 17:41:04
# Date/Publication: 2018-07-13 15:20:03 UTC
# NeedsCompilation: no
# Packaged: 2018-05-24 17:55:14 UTC; rforge

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
