travis:
  secure:
    BINSTAR_TOKEN: Jv2Z8aiciywt4UAy8pVl4K9rkqngy/XQTZpXK+P43EhiVUg6knI5AtYlVrJZnKuGAqCeiK7w0YbJq6/5MGPOJ6vF7ahxKvDDgj0MjeaL0oEDPQ7yPxB5fWSyUqjVDJKAucBE+/ryp1xY6FK339ghRBYsVPRPC28/jNEV5KU9pEIvHcPqaQSqgfBG/NUhhzTK8btS9h9KdnUZu3SJAuC5VV15j3M5UkpYo+YuDlARCYmr1P4icOMTH4XePC53f11Oct794NE2ncdNpGIKzYbAE/fpil7wWijTMYo0x0pgR3/ZyO5dzEqxhaZt0FswGMadwb/RjCrP1g4KFzZUxqDgimLwZnbP+c7OUxjE6SWXnNGMFLALho4F+N7UorfVos4HtbX/BJbrt0Y21uwWOIDzdCUde7yYjSLPK2vXImREAPComb3BN7p2ldb1Pw6ehZLm5swaJZKUQ7qQC8KA5g4QnXAeAyeuvRApz/RaPixOg4B26qvHXI5tqxAfwt2TYR3wpRoDbCwZlYOMHgeTJNOeoZAdYkqOHR1GOTZ9DhPJZxfrKLwAWfJ49skGjUiHoUR/E8JMk/SSU0RRgsxqnjwkfISG3bpjQZ+y0RklNg8OIfb72EoCVZYSafFUpirf8O1Tkw3e/mxWrUZ+edqhCn3kcRCLl4LDHI0dnS8FC4fZ7L0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
