travis:
  secure:
    BINSTAR_TOKEN: nGJzOORXExGloXJxP8uxu1kPwV/awSVVvhDwFlQcQGdwA+RwxZHlwwMjL3NUofUNIWzmo9fp1qWXm9tvCLt6mEDHEkKWHY6YTkfN+qcPEhBats0akaCrMvRdPEZVS57Y8lo/IqfhXTXJf10aSdaEQpY8SzvgnxKs1VbKeHWww94gONxXjFhParZuu6Z2FL6BWjxdnSkx1yx7TnyvPUT4FJbD7Ypn+lhzSFUQyy9qFFU+v8+LGKFjGhVvAvEdEwtkjthO5I8vG9MqaMk6+a6toWFfFIGeeFA+OFJR0TlsJ9w7H0s2AXz7at2VPsL1nMcDeqrl7C29P4+uagjH5wnadOkI8xQh1e0HGi3T8QahUfmxuf2KYxZJVVbPZmFmcoDaswRKUsvme21k1zYvYxYzLRV0q/YqRXg0lLS/kljKa1Q9xzM2rr10xzfP68n+GMWdqEp5W5JjQb2lCr3bbzO+f2bCDtftwLaLosqZbnnYUj7A+5aR4I1pm7Q+B3SMR1Bv+gq6xBe6OLYNhlAh5MeWIh2aHRB2S4xSViMA8UVlhYD4iHFiPRT++Gm4tZQOQCLSSpD4XsTJP8xrTUUYKBKz+gvluX3GwB4GzpwQfpdfVnDLSowo/H5GdkEeVq/tMbjvcr1+0fti7BxHsyqtjg3IXnD/8Z0pT2uYX449D8SJqXs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
